// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisionProData.proto

#include "VisionProData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace RobotTeleoperate {
PROTOBUF_CONSTEXPR Matrix4d::Matrix4d(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Matrix4dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Matrix4dDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Matrix4dDefaultTypeInternal() {}
  union {
    Matrix4d _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Matrix4dDefaultTypeInternal _Matrix4d_default_instance_;
PROTOBUF_CONSTEXPR Point3d::Point3d(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Point3dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Point3dDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Point3dDefaultTypeInternal() {}
  union {
    Point3d _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Point3dDefaultTypeInternal _Point3d_default_instance_;
PROTOBUF_CONSTEXPR HandPositions::HandPositions(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.joints_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HandPositionsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HandPositionsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HandPositionsDefaultTypeInternal() {}
  union {
    HandPositions _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HandPositionsDefaultTypeInternal _HandPositions_default_instance_;
PROTOBUF_CONSTEXPR HandGesture::HandGesture(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pinchvalue_)*/0
  , /*decltype(_impl_.pinchstate_)*/false
  , /*decltype(_impl_.squeezestate_)*/false
  , /*decltype(_impl_.squeezevalue_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HandGestureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HandGestureDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HandGestureDefaultTypeInternal() {}
  union {
    HandGesture _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HandGestureDefaultTypeInternal _HandGesture_default_instance_;
PROTOBUF_CONSTEXPR VisionProData::VisionProData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.headpose_)*/nullptr
  , /*decltype(_impl_.leftarmpose_)*/nullptr
  , /*decltype(_impl_.rightarmpose_)*/nullptr
  , /*decltype(_impl_.lefthandpositions_)*/nullptr
  , /*decltype(_impl_.righthandpositions_)*/nullptr
  , /*decltype(_impl_.lefthandgesture_)*/nullptr
  , /*decltype(_impl_.righthandgesture_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VisionProDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VisionProDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VisionProDataDefaultTypeInternal() {}
  union {
    VisionProData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VisionProDataDefaultTypeInternal _VisionProData_default_instance_;
}  // namespace RobotTeleoperate
static ::_pb::Metadata file_level_metadata_VisionProData_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_VisionProData_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_VisionProData_2eproto = nullptr;

const uint32_t TableStruct_VisionProData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::Matrix4d, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::Matrix4d, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::Point3d, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::Point3d, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::Point3d, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::Point3d, _impl_.z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandPositions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandPositions, _impl_.joints_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandGesture, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandGesture, _impl_.pinchstate_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandGesture, _impl_.pinchvalue_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandGesture, _impl_.squeezestate_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::HandGesture, _impl_.squeezevalue_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.headpose_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.leftarmpose_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.rightarmpose_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.lefthandpositions_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.righthandpositions_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.lefthandgesture_),
  PROTOBUF_FIELD_OFFSET(::RobotTeleoperate::VisionProData, _impl_.righthandgesture_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::RobotTeleoperate::Matrix4d)},
  { 7, -1, -1, sizeof(::RobotTeleoperate::Point3d)},
  { 16, -1, -1, sizeof(::RobotTeleoperate::HandPositions)},
  { 23, -1, -1, sizeof(::RobotTeleoperate::HandGesture)},
  { 33, -1, -1, sizeof(::RobotTeleoperate::VisionProData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::RobotTeleoperate::_Matrix4d_default_instance_._instance,
  &::RobotTeleoperate::_Point3d_default_instance_._instance,
  &::RobotTeleoperate::_HandPositions_default_instance_._instance,
  &::RobotTeleoperate::_HandGesture_default_instance_._instance,
  &::RobotTeleoperate::_VisionProData_default_instance_._instance,
};

const char descriptor_table_protodef_VisionProData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023VisionProData.proto\022\020RobotTeleoperate\""
  "\030\n\010Matrix4d\022\014\n\004data\030\001 \003(\001\"*\n\007Point3d\022\t\n\001"
  "x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\":\n\rHandPos"
  "itions\022)\n\006joints\030\001 \003(\0132\031.RobotTeleoperat"
  "e.Point3d\"a\n\013HandGesture\022\022\n\npinchState\030\001"
  " \001(\010\022\022\n\npinchValue\030\002 \001(\002\022\024\n\014SqueezeState"
  "\030\003 \001(\010\022\024\n\014SqueezeValue\030\004 \001(\002\"\212\003\n\rVisionP"
  "roData\022,\n\010headPose\030\001 \001(\0132\032.RobotTeleoper"
  "ate.Matrix4d\022/\n\013leftArmPose\030\002 \001(\0132\032.Robo"
  "tTeleoperate.Matrix4d\0220\n\014rightArmPose\030\003 "
  "\001(\0132\032.RobotTeleoperate.Matrix4d\022:\n\021leftH"
  "andPositions\030\004 \001(\0132\037.RobotTeleoperate.Ha"
  "ndPositions\022;\n\022rightHandPositions\030\005 \001(\0132"
  "\037.RobotTeleoperate.HandPositions\0226\n\017left"
  "HandGesture\030\006 \001(\0132\035.RobotTeleoperate.Han"
  "dGesture\0227\n\020rightHandGesture\030\007 \001(\0132\035.Rob"
  "otTeleoperate.HandGestureb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_VisionProData_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_VisionProData_2eproto = {
    false, false, 673, descriptor_table_protodef_VisionProData_2eproto,
    "VisionProData.proto",
    &descriptor_table_VisionProData_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_VisionProData_2eproto::offsets,
    file_level_metadata_VisionProData_2eproto, file_level_enum_descriptors_VisionProData_2eproto,
    file_level_service_descriptors_VisionProData_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_VisionProData_2eproto_getter() {
  return &descriptor_table_VisionProData_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_VisionProData_2eproto(&descriptor_table_VisionProData_2eproto);
namespace RobotTeleoperate {

// ===================================================================

class Matrix4d::_Internal {
 public:
};

Matrix4d::Matrix4d(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RobotTeleoperate.Matrix4d)
}
Matrix4d::Matrix4d(const Matrix4d& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Matrix4d* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:RobotTeleoperate.Matrix4d)
}

inline void Matrix4d::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Matrix4d::~Matrix4d() {
  // @@protoc_insertion_point(destructor:RobotTeleoperate.Matrix4d)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Matrix4d::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedField();
}

void Matrix4d::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Matrix4d::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotTeleoperate.Matrix4d)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Matrix4d::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated double data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 9) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Matrix4d::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotTeleoperate.Matrix4d)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated double data = 1;
  if (this->_internal_data_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotTeleoperate.Matrix4d)
  return target;
}

size_t Matrix4d::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotTeleoperate.Matrix4d)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double data = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Matrix4d::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Matrix4d::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Matrix4d::GetClassData() const { return &_class_data_; }


void Matrix4d::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Matrix4d*>(&to_msg);
  auto& from = static_cast<const Matrix4d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotTeleoperate.Matrix4d)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Matrix4d::CopyFrom(const Matrix4d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotTeleoperate.Matrix4d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Matrix4d::IsInitialized() const {
  return true;
}

void Matrix4d::InternalSwap(Matrix4d* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Matrix4d::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_VisionProData_2eproto_getter, &descriptor_table_VisionProData_2eproto_once,
      file_level_metadata_VisionProData_2eproto[0]);
}

// ===================================================================

class Point3d::_Internal {
 public:
};

Point3d::Point3d(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RobotTeleoperate.Point3d)
}
Point3d::Point3d(const Point3d& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Point3d* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.z_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  // @@protoc_insertion_point(copy_constructor:RobotTeleoperate.Point3d)
}

inline void Point3d::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Point3d::~Point3d() {
  // @@protoc_insertion_point(destructor:RobotTeleoperate.Point3d)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Point3d::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Point3d::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Point3d::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotTeleoperate.Point3d)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Point3d::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Point3d::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotTeleoperate.Point3d)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_x(), target);
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_y(), target);
  }

  // double z = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = this->_internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotTeleoperate.Point3d)
  return target;
}

size_t Point3d::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotTeleoperate.Point3d)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 8;
  }

  // double z = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = this->_internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Point3d::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Point3d::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Point3d::GetClassData() const { return &_class_data_; }


void Point3d::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Point3d*>(&to_msg);
  auto& from = static_cast<const Point3d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotTeleoperate.Point3d)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = from._internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = from._internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = from._internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Point3d::CopyFrom(const Point3d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotTeleoperate.Point3d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Point3d::IsInitialized() const {
  return true;
}

void Point3d::InternalSwap(Point3d* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Point3d, _impl_.z_)
      + sizeof(Point3d::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Point3d, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Point3d::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_VisionProData_2eproto_getter, &descriptor_table_VisionProData_2eproto_once,
      file_level_metadata_VisionProData_2eproto[1]);
}

// ===================================================================

class HandPositions::_Internal {
 public:
};

HandPositions::HandPositions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RobotTeleoperate.HandPositions)
}
HandPositions::HandPositions(const HandPositions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HandPositions* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.joints_){from._impl_.joints_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:RobotTeleoperate.HandPositions)
}

inline void HandPositions::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.joints_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HandPositions::~HandPositions() {
  // @@protoc_insertion_point(destructor:RobotTeleoperate.HandPositions)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HandPositions::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.joints_.~RepeatedPtrField();
}

void HandPositions::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HandPositions::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotTeleoperate.HandPositions)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.joints_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HandPositions::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .RobotTeleoperate.Point3d joints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_joints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HandPositions::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotTeleoperate.HandPositions)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .RobotTeleoperate.Point3d joints = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_joints_size()); i < n; i++) {
    const auto& repfield = this->_internal_joints(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotTeleoperate.HandPositions)
  return target;
}

size_t HandPositions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotTeleoperate.HandPositions)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .RobotTeleoperate.Point3d joints = 1;
  total_size += 1UL * this->_internal_joints_size();
  for (const auto& msg : this->_impl_.joints_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HandPositions::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HandPositions::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HandPositions::GetClassData() const { return &_class_data_; }


void HandPositions::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HandPositions*>(&to_msg);
  auto& from = static_cast<const HandPositions&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotTeleoperate.HandPositions)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.joints_.MergeFrom(from._impl_.joints_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HandPositions::CopyFrom(const HandPositions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotTeleoperate.HandPositions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HandPositions::IsInitialized() const {
  return true;
}

void HandPositions::InternalSwap(HandPositions* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.joints_.InternalSwap(&other->_impl_.joints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HandPositions::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_VisionProData_2eproto_getter, &descriptor_table_VisionProData_2eproto_once,
      file_level_metadata_VisionProData_2eproto[2]);
}

// ===================================================================

class HandGesture::_Internal {
 public:
};

HandGesture::HandGesture(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RobotTeleoperate.HandGesture)
}
HandGesture::HandGesture(const HandGesture& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HandGesture* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pinchvalue_){}
    , decltype(_impl_.pinchstate_){}
    , decltype(_impl_.squeezestate_){}
    , decltype(_impl_.squeezevalue_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.pinchvalue_, &from._impl_.pinchvalue_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.squeezevalue_) -
    reinterpret_cast<char*>(&_impl_.pinchvalue_)) + sizeof(_impl_.squeezevalue_));
  // @@protoc_insertion_point(copy_constructor:RobotTeleoperate.HandGesture)
}

inline void HandGesture::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pinchvalue_){0}
    , decltype(_impl_.pinchstate_){false}
    , decltype(_impl_.squeezestate_){false}
    , decltype(_impl_.squeezevalue_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HandGesture::~HandGesture() {
  // @@protoc_insertion_point(destructor:RobotTeleoperate.HandGesture)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HandGesture::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HandGesture::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HandGesture::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotTeleoperate.HandGesture)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.pinchvalue_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.squeezevalue_) -
      reinterpret_cast<char*>(&_impl_.pinchvalue_)) + sizeof(_impl_.squeezevalue_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HandGesture::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool pinchState = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.pinchstate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float pinchValue = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.pinchvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool SqueezeState = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.squeezestate_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float SqueezeValue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.squeezevalue_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HandGesture::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotTeleoperate.HandGesture)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool pinchState = 1;
  if (this->_internal_pinchstate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_pinchstate(), target);
  }

  // float pinchValue = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pinchvalue = this->_internal_pinchvalue();
  uint32_t raw_pinchvalue;
  memcpy(&raw_pinchvalue, &tmp_pinchvalue, sizeof(tmp_pinchvalue));
  if (raw_pinchvalue != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_pinchvalue(), target);
  }

  // bool SqueezeState = 3;
  if (this->_internal_squeezestate() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_squeezestate(), target);
  }

  // float SqueezeValue = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_squeezevalue = this->_internal_squeezevalue();
  uint32_t raw_squeezevalue;
  memcpy(&raw_squeezevalue, &tmp_squeezevalue, sizeof(tmp_squeezevalue));
  if (raw_squeezevalue != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_squeezevalue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotTeleoperate.HandGesture)
  return target;
}

size_t HandGesture::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotTeleoperate.HandGesture)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float pinchValue = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pinchvalue = this->_internal_pinchvalue();
  uint32_t raw_pinchvalue;
  memcpy(&raw_pinchvalue, &tmp_pinchvalue, sizeof(tmp_pinchvalue));
  if (raw_pinchvalue != 0) {
    total_size += 1 + 4;
  }

  // bool pinchState = 1;
  if (this->_internal_pinchstate() != 0) {
    total_size += 1 + 1;
  }

  // bool SqueezeState = 3;
  if (this->_internal_squeezestate() != 0) {
    total_size += 1 + 1;
  }

  // float SqueezeValue = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_squeezevalue = this->_internal_squeezevalue();
  uint32_t raw_squeezevalue;
  memcpy(&raw_squeezevalue, &tmp_squeezevalue, sizeof(tmp_squeezevalue));
  if (raw_squeezevalue != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HandGesture::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HandGesture::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HandGesture::GetClassData() const { return &_class_data_; }


void HandGesture::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HandGesture*>(&to_msg);
  auto& from = static_cast<const HandGesture&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotTeleoperate.HandGesture)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pinchvalue = from._internal_pinchvalue();
  uint32_t raw_pinchvalue;
  memcpy(&raw_pinchvalue, &tmp_pinchvalue, sizeof(tmp_pinchvalue));
  if (raw_pinchvalue != 0) {
    _this->_internal_set_pinchvalue(from._internal_pinchvalue());
  }
  if (from._internal_pinchstate() != 0) {
    _this->_internal_set_pinchstate(from._internal_pinchstate());
  }
  if (from._internal_squeezestate() != 0) {
    _this->_internal_set_squeezestate(from._internal_squeezestate());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_squeezevalue = from._internal_squeezevalue();
  uint32_t raw_squeezevalue;
  memcpy(&raw_squeezevalue, &tmp_squeezevalue, sizeof(tmp_squeezevalue));
  if (raw_squeezevalue != 0) {
    _this->_internal_set_squeezevalue(from._internal_squeezevalue());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HandGesture::CopyFrom(const HandGesture& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotTeleoperate.HandGesture)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HandGesture::IsInitialized() const {
  return true;
}

void HandGesture::InternalSwap(HandGesture* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HandGesture, _impl_.squeezevalue_)
      + sizeof(HandGesture::_impl_.squeezevalue_)
      - PROTOBUF_FIELD_OFFSET(HandGesture, _impl_.pinchvalue_)>(
          reinterpret_cast<char*>(&_impl_.pinchvalue_),
          reinterpret_cast<char*>(&other->_impl_.pinchvalue_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HandGesture::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_VisionProData_2eproto_getter, &descriptor_table_VisionProData_2eproto_once,
      file_level_metadata_VisionProData_2eproto[3]);
}

// ===================================================================

class VisionProData::_Internal {
 public:
  static const ::RobotTeleoperate::Matrix4d& headpose(const VisionProData* msg);
  static const ::RobotTeleoperate::Matrix4d& leftarmpose(const VisionProData* msg);
  static const ::RobotTeleoperate::Matrix4d& rightarmpose(const VisionProData* msg);
  static const ::RobotTeleoperate::HandPositions& lefthandpositions(const VisionProData* msg);
  static const ::RobotTeleoperate::HandPositions& righthandpositions(const VisionProData* msg);
  static const ::RobotTeleoperate::HandGesture& lefthandgesture(const VisionProData* msg);
  static const ::RobotTeleoperate::HandGesture& righthandgesture(const VisionProData* msg);
};

const ::RobotTeleoperate::Matrix4d&
VisionProData::_Internal::headpose(const VisionProData* msg) {
  return *msg->_impl_.headpose_;
}
const ::RobotTeleoperate::Matrix4d&
VisionProData::_Internal::leftarmpose(const VisionProData* msg) {
  return *msg->_impl_.leftarmpose_;
}
const ::RobotTeleoperate::Matrix4d&
VisionProData::_Internal::rightarmpose(const VisionProData* msg) {
  return *msg->_impl_.rightarmpose_;
}
const ::RobotTeleoperate::HandPositions&
VisionProData::_Internal::lefthandpositions(const VisionProData* msg) {
  return *msg->_impl_.lefthandpositions_;
}
const ::RobotTeleoperate::HandPositions&
VisionProData::_Internal::righthandpositions(const VisionProData* msg) {
  return *msg->_impl_.righthandpositions_;
}
const ::RobotTeleoperate::HandGesture&
VisionProData::_Internal::lefthandgesture(const VisionProData* msg) {
  return *msg->_impl_.lefthandgesture_;
}
const ::RobotTeleoperate::HandGesture&
VisionProData::_Internal::righthandgesture(const VisionProData* msg) {
  return *msg->_impl_.righthandgesture_;
}
VisionProData::VisionProData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RobotTeleoperate.VisionProData)
}
VisionProData::VisionProData(const VisionProData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VisionProData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.headpose_){nullptr}
    , decltype(_impl_.leftarmpose_){nullptr}
    , decltype(_impl_.rightarmpose_){nullptr}
    , decltype(_impl_.lefthandpositions_){nullptr}
    , decltype(_impl_.righthandpositions_){nullptr}
    , decltype(_impl_.lefthandgesture_){nullptr}
    , decltype(_impl_.righthandgesture_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_headpose()) {
    _this->_impl_.headpose_ = new ::RobotTeleoperate::Matrix4d(*from._impl_.headpose_);
  }
  if (from._internal_has_leftarmpose()) {
    _this->_impl_.leftarmpose_ = new ::RobotTeleoperate::Matrix4d(*from._impl_.leftarmpose_);
  }
  if (from._internal_has_rightarmpose()) {
    _this->_impl_.rightarmpose_ = new ::RobotTeleoperate::Matrix4d(*from._impl_.rightarmpose_);
  }
  if (from._internal_has_lefthandpositions()) {
    _this->_impl_.lefthandpositions_ = new ::RobotTeleoperate::HandPositions(*from._impl_.lefthandpositions_);
  }
  if (from._internal_has_righthandpositions()) {
    _this->_impl_.righthandpositions_ = new ::RobotTeleoperate::HandPositions(*from._impl_.righthandpositions_);
  }
  if (from._internal_has_lefthandgesture()) {
    _this->_impl_.lefthandgesture_ = new ::RobotTeleoperate::HandGesture(*from._impl_.lefthandgesture_);
  }
  if (from._internal_has_righthandgesture()) {
    _this->_impl_.righthandgesture_ = new ::RobotTeleoperate::HandGesture(*from._impl_.righthandgesture_);
  }
  // @@protoc_insertion_point(copy_constructor:RobotTeleoperate.VisionProData)
}

inline void VisionProData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.headpose_){nullptr}
    , decltype(_impl_.leftarmpose_){nullptr}
    , decltype(_impl_.rightarmpose_){nullptr}
    , decltype(_impl_.lefthandpositions_){nullptr}
    , decltype(_impl_.righthandpositions_){nullptr}
    , decltype(_impl_.lefthandgesture_){nullptr}
    , decltype(_impl_.righthandgesture_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VisionProData::~VisionProData() {
  // @@protoc_insertion_point(destructor:RobotTeleoperate.VisionProData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VisionProData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.headpose_;
  if (this != internal_default_instance()) delete _impl_.leftarmpose_;
  if (this != internal_default_instance()) delete _impl_.rightarmpose_;
  if (this != internal_default_instance()) delete _impl_.lefthandpositions_;
  if (this != internal_default_instance()) delete _impl_.righthandpositions_;
  if (this != internal_default_instance()) delete _impl_.lefthandgesture_;
  if (this != internal_default_instance()) delete _impl_.righthandgesture_;
}

void VisionProData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VisionProData::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotTeleoperate.VisionProData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.headpose_ != nullptr) {
    delete _impl_.headpose_;
  }
  _impl_.headpose_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.leftarmpose_ != nullptr) {
    delete _impl_.leftarmpose_;
  }
  _impl_.leftarmpose_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.rightarmpose_ != nullptr) {
    delete _impl_.rightarmpose_;
  }
  _impl_.rightarmpose_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.lefthandpositions_ != nullptr) {
    delete _impl_.lefthandpositions_;
  }
  _impl_.lefthandpositions_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.righthandpositions_ != nullptr) {
    delete _impl_.righthandpositions_;
  }
  _impl_.righthandpositions_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.lefthandgesture_ != nullptr) {
    delete _impl_.lefthandgesture_;
  }
  _impl_.lefthandgesture_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.righthandgesture_ != nullptr) {
    delete _impl_.righthandgesture_;
  }
  _impl_.righthandgesture_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VisionProData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .RobotTeleoperate.Matrix4d headPose = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_headpose(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RobotTeleoperate.Matrix4d leftArmPose = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_leftarmpose(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RobotTeleoperate.Matrix4d rightArmPose = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_rightarmpose(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RobotTeleoperate.HandPositions leftHandPositions = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_lefthandpositions(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RobotTeleoperate.HandPositions rightHandPositions = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_righthandpositions(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RobotTeleoperate.HandGesture leftHandGesture = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_lefthandgesture(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .RobotTeleoperate.HandGesture rightHandGesture = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_righthandgesture(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VisionProData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotTeleoperate.VisionProData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .RobotTeleoperate.Matrix4d headPose = 1;
  if (this->_internal_has_headpose()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::headpose(this),
        _Internal::headpose(this).GetCachedSize(), target, stream);
  }

  // .RobotTeleoperate.Matrix4d leftArmPose = 2;
  if (this->_internal_has_leftarmpose()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::leftarmpose(this),
        _Internal::leftarmpose(this).GetCachedSize(), target, stream);
  }

  // .RobotTeleoperate.Matrix4d rightArmPose = 3;
  if (this->_internal_has_rightarmpose()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::rightarmpose(this),
        _Internal::rightarmpose(this).GetCachedSize(), target, stream);
  }

  // .RobotTeleoperate.HandPositions leftHandPositions = 4;
  if (this->_internal_has_lefthandpositions()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::lefthandpositions(this),
        _Internal::lefthandpositions(this).GetCachedSize(), target, stream);
  }

  // .RobotTeleoperate.HandPositions rightHandPositions = 5;
  if (this->_internal_has_righthandpositions()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::righthandpositions(this),
        _Internal::righthandpositions(this).GetCachedSize(), target, stream);
  }

  // .RobotTeleoperate.HandGesture leftHandGesture = 6;
  if (this->_internal_has_lefthandgesture()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::lefthandgesture(this),
        _Internal::lefthandgesture(this).GetCachedSize(), target, stream);
  }

  // .RobotTeleoperate.HandGesture rightHandGesture = 7;
  if (this->_internal_has_righthandgesture()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::righthandgesture(this),
        _Internal::righthandgesture(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotTeleoperate.VisionProData)
  return target;
}

size_t VisionProData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotTeleoperate.VisionProData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .RobotTeleoperate.Matrix4d headPose = 1;
  if (this->_internal_has_headpose()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.headpose_);
  }

  // .RobotTeleoperate.Matrix4d leftArmPose = 2;
  if (this->_internal_has_leftarmpose()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.leftarmpose_);
  }

  // .RobotTeleoperate.Matrix4d rightArmPose = 3;
  if (this->_internal_has_rightarmpose()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.rightarmpose_);
  }

  // .RobotTeleoperate.HandPositions leftHandPositions = 4;
  if (this->_internal_has_lefthandpositions()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.lefthandpositions_);
  }

  // .RobotTeleoperate.HandPositions rightHandPositions = 5;
  if (this->_internal_has_righthandpositions()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.righthandpositions_);
  }

  // .RobotTeleoperate.HandGesture leftHandGesture = 6;
  if (this->_internal_has_lefthandgesture()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.lefthandgesture_);
  }

  // .RobotTeleoperate.HandGesture rightHandGesture = 7;
  if (this->_internal_has_righthandgesture()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.righthandgesture_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VisionProData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VisionProData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VisionProData::GetClassData() const { return &_class_data_; }


void VisionProData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VisionProData*>(&to_msg);
  auto& from = static_cast<const VisionProData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotTeleoperate.VisionProData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_headpose()) {
    _this->_internal_mutable_headpose()->::RobotTeleoperate::Matrix4d::MergeFrom(
        from._internal_headpose());
  }
  if (from._internal_has_leftarmpose()) {
    _this->_internal_mutable_leftarmpose()->::RobotTeleoperate::Matrix4d::MergeFrom(
        from._internal_leftarmpose());
  }
  if (from._internal_has_rightarmpose()) {
    _this->_internal_mutable_rightarmpose()->::RobotTeleoperate::Matrix4d::MergeFrom(
        from._internal_rightarmpose());
  }
  if (from._internal_has_lefthandpositions()) {
    _this->_internal_mutable_lefthandpositions()->::RobotTeleoperate::HandPositions::MergeFrom(
        from._internal_lefthandpositions());
  }
  if (from._internal_has_righthandpositions()) {
    _this->_internal_mutable_righthandpositions()->::RobotTeleoperate::HandPositions::MergeFrom(
        from._internal_righthandpositions());
  }
  if (from._internal_has_lefthandgesture()) {
    _this->_internal_mutable_lefthandgesture()->::RobotTeleoperate::HandGesture::MergeFrom(
        from._internal_lefthandgesture());
  }
  if (from._internal_has_righthandgesture()) {
    _this->_internal_mutable_righthandgesture()->::RobotTeleoperate::HandGesture::MergeFrom(
        from._internal_righthandgesture());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VisionProData::CopyFrom(const VisionProData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotTeleoperate.VisionProData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VisionProData::IsInitialized() const {
  return true;
}

void VisionProData::InternalSwap(VisionProData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VisionProData, _impl_.righthandgesture_)
      + sizeof(VisionProData::_impl_.righthandgesture_)
      - PROTOBUF_FIELD_OFFSET(VisionProData, _impl_.headpose_)>(
          reinterpret_cast<char*>(&_impl_.headpose_),
          reinterpret_cast<char*>(&other->_impl_.headpose_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VisionProData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_VisionProData_2eproto_getter, &descriptor_table_VisionProData_2eproto_once,
      file_level_metadata_VisionProData_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace RobotTeleoperate
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::RobotTeleoperate::Matrix4d*
Arena::CreateMaybeMessage< ::RobotTeleoperate::Matrix4d >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RobotTeleoperate::Matrix4d >(arena);
}
template<> PROTOBUF_NOINLINE ::RobotTeleoperate::Point3d*
Arena::CreateMaybeMessage< ::RobotTeleoperate::Point3d >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RobotTeleoperate::Point3d >(arena);
}
template<> PROTOBUF_NOINLINE ::RobotTeleoperate::HandPositions*
Arena::CreateMaybeMessage< ::RobotTeleoperate::HandPositions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RobotTeleoperate::HandPositions >(arena);
}
template<> PROTOBUF_NOINLINE ::RobotTeleoperate::HandGesture*
Arena::CreateMaybeMessage< ::RobotTeleoperate::HandGesture >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RobotTeleoperate::HandGesture >(arena);
}
template<> PROTOBUF_NOINLINE ::RobotTeleoperate::VisionProData*
Arena::CreateMaybeMessage< ::RobotTeleoperate::VisionProData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RobotTeleoperate::VisionProData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
