// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisionProData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_VisionProData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_VisionProData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_VisionProData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_VisionProData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_VisionProData_2eproto;
namespace RobotTeleoperate {
class HandPositions;
struct HandPositionsDefaultTypeInternal;
extern HandPositionsDefaultTypeInternal _HandPositions_default_instance_;
class Matrix4d;
struct Matrix4dDefaultTypeInternal;
extern Matrix4dDefaultTypeInternal _Matrix4d_default_instance_;
class Point3d;
struct Point3dDefaultTypeInternal;
extern Point3dDefaultTypeInternal _Point3d_default_instance_;
class VisionProData;
struct VisionProDataDefaultTypeInternal;
extern VisionProDataDefaultTypeInternal _VisionProData_default_instance_;
}  // namespace RobotTeleoperate
PROTOBUF_NAMESPACE_OPEN
template<> ::RobotTeleoperate::HandPositions* Arena::CreateMaybeMessage<::RobotTeleoperate::HandPositions>(Arena*);
template<> ::RobotTeleoperate::Matrix4d* Arena::CreateMaybeMessage<::RobotTeleoperate::Matrix4d>(Arena*);
template<> ::RobotTeleoperate::Point3d* Arena::CreateMaybeMessage<::RobotTeleoperate::Point3d>(Arena*);
template<> ::RobotTeleoperate::VisionProData* Arena::CreateMaybeMessage<::RobotTeleoperate::VisionProData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace RobotTeleoperate {

// ===================================================================

class Matrix4d final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RobotTeleoperate.Matrix4d) */ {
 public:
  inline Matrix4d() : Matrix4d(nullptr) {}
  ~Matrix4d() override;
  explicit PROTOBUF_CONSTEXPR Matrix4d(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Matrix4d(const Matrix4d& from);
  Matrix4d(Matrix4d&& from) noexcept
    : Matrix4d() {
    *this = ::std::move(from);
  }

  inline Matrix4d& operator=(const Matrix4d& from) {
    CopyFrom(from);
    return *this;
  }
  inline Matrix4d& operator=(Matrix4d&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Matrix4d& default_instance() {
    return *internal_default_instance();
  }
  static inline const Matrix4d* internal_default_instance() {
    return reinterpret_cast<const Matrix4d*>(
               &_Matrix4d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Matrix4d& a, Matrix4d& b) {
    a.Swap(&b);
  }
  inline void Swap(Matrix4d* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Matrix4d* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Matrix4d* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Matrix4d>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Matrix4d& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Matrix4d& from) {
    Matrix4d::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Matrix4d* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RobotTeleoperate.Matrix4d";
  }
  protected:
  explicit Matrix4d(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated double data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  double _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_data() const;
  void _internal_add_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_data();
  public:
  double data(int index) const;
  void set_data(int index, double value);
  void add_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:RobotTeleoperate.Matrix4d)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_VisionProData_2eproto;
};
// -------------------------------------------------------------------

class Point3d final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RobotTeleoperate.Point3d) */ {
 public:
  inline Point3d() : Point3d(nullptr) {}
  ~Point3d() override;
  explicit PROTOBUF_CONSTEXPR Point3d(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point3d(const Point3d& from);
  Point3d(Point3d&& from) noexcept
    : Point3d() {
    *this = ::std::move(from);
  }

  inline Point3d& operator=(const Point3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point3d& operator=(Point3d&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point3d& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point3d* internal_default_instance() {
    return reinterpret_cast<const Point3d*>(
               &_Point3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Point3d& a, Point3d& b) {
    a.Swap(&b);
  }
  inline void Swap(Point3d* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point3d* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point3d* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point3d>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point3d& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point3d& from) {
    Point3d::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point3d* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RobotTeleoperate.Point3d";
  }
  protected:
  explicit Point3d(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:RobotTeleoperate.Point3d)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_VisionProData_2eproto;
};
// -------------------------------------------------------------------

class HandPositions final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RobotTeleoperate.HandPositions) */ {
 public:
  inline HandPositions() : HandPositions(nullptr) {}
  ~HandPositions() override;
  explicit PROTOBUF_CONSTEXPR HandPositions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HandPositions(const HandPositions& from);
  HandPositions(HandPositions&& from) noexcept
    : HandPositions() {
    *this = ::std::move(from);
  }

  inline HandPositions& operator=(const HandPositions& from) {
    CopyFrom(from);
    return *this;
  }
  inline HandPositions& operator=(HandPositions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HandPositions& default_instance() {
    return *internal_default_instance();
  }
  static inline const HandPositions* internal_default_instance() {
    return reinterpret_cast<const HandPositions*>(
               &_HandPositions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HandPositions& a, HandPositions& b) {
    a.Swap(&b);
  }
  inline void Swap(HandPositions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HandPositions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HandPositions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HandPositions>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HandPositions& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HandPositions& from) {
    HandPositions::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HandPositions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RobotTeleoperate.HandPositions";
  }
  protected:
  explicit HandPositions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJointsFieldNumber = 1,
  };
  // repeated .RobotTeleoperate.Point3d joints = 1;
  int joints_size() const;
  private:
  int _internal_joints_size() const;
  public:
  void clear_joints();
  ::RobotTeleoperate::Point3d* mutable_joints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RobotTeleoperate::Point3d >*
      mutable_joints();
  private:
  const ::RobotTeleoperate::Point3d& _internal_joints(int index) const;
  ::RobotTeleoperate::Point3d* _internal_add_joints();
  public:
  const ::RobotTeleoperate::Point3d& joints(int index) const;
  ::RobotTeleoperate::Point3d* add_joints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RobotTeleoperate::Point3d >&
      joints() const;

  // @@protoc_insertion_point(class_scope:RobotTeleoperate.HandPositions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RobotTeleoperate::Point3d > joints_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_VisionProData_2eproto;
};
// -------------------------------------------------------------------

class VisionProData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RobotTeleoperate.VisionProData) */ {
 public:
  inline VisionProData() : VisionProData(nullptr) {}
  ~VisionProData() override;
  explicit PROTOBUF_CONSTEXPR VisionProData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VisionProData(const VisionProData& from);
  VisionProData(VisionProData&& from) noexcept
    : VisionProData() {
    *this = ::std::move(from);
  }

  inline VisionProData& operator=(const VisionProData& from) {
    CopyFrom(from);
    return *this;
  }
  inline VisionProData& operator=(VisionProData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VisionProData& default_instance() {
    return *internal_default_instance();
  }
  static inline const VisionProData* internal_default_instance() {
    return reinterpret_cast<const VisionProData*>(
               &_VisionProData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(VisionProData& a, VisionProData& b) {
    a.Swap(&b);
  }
  inline void Swap(VisionProData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VisionProData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VisionProData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VisionProData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VisionProData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VisionProData& from) {
    VisionProData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VisionProData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RobotTeleoperate.VisionProData";
  }
  protected:
  explicit VisionProData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadPzoseFieldNumber = 1,
    kLeftArmPoseFieldNumber = 2,
    kRightArmPoseFieldNumber = 3,
    kLeftHandPositionsFieldNumber = 4,
    kRightHandPositionsFieldNumber = 5,
  };
  // .RobotTeleoperate.Matrix4d headPzose = 1;
  bool has_headpzose() const;
  private:
  bool _internal_has_headpzose() const;
  public:
  void clear_headpzose();
  const ::RobotTeleoperate::Matrix4d& headpzose() const;
  PROTOBUF_NODISCARD ::RobotTeleoperate::Matrix4d* release_headpzose();
  ::RobotTeleoperate::Matrix4d* mutable_headpzose();
  void set_allocated_headpzose(::RobotTeleoperate::Matrix4d* headpzose);
  private:
  const ::RobotTeleoperate::Matrix4d& _internal_headpzose() const;
  ::RobotTeleoperate::Matrix4d* _internal_mutable_headpzose();
  public:
  void unsafe_arena_set_allocated_headpzose(
      ::RobotTeleoperate::Matrix4d* headpzose);
  ::RobotTeleoperate::Matrix4d* unsafe_arena_release_headpzose();

  // .RobotTeleoperate.Matrix4d leftArmPose = 2;
  bool has_leftarmpose() const;
  private:
  bool _internal_has_leftarmpose() const;
  public:
  void clear_leftarmpose();
  const ::RobotTeleoperate::Matrix4d& leftarmpose() const;
  PROTOBUF_NODISCARD ::RobotTeleoperate::Matrix4d* release_leftarmpose();
  ::RobotTeleoperate::Matrix4d* mutable_leftarmpose();
  void set_allocated_leftarmpose(::RobotTeleoperate::Matrix4d* leftarmpose);
  private:
  const ::RobotTeleoperate::Matrix4d& _internal_leftarmpose() const;
  ::RobotTeleoperate::Matrix4d* _internal_mutable_leftarmpose();
  public:
  void unsafe_arena_set_allocated_leftarmpose(
      ::RobotTeleoperate::Matrix4d* leftarmpose);
  ::RobotTeleoperate::Matrix4d* unsafe_arena_release_leftarmpose();

  // .RobotTeleoperate.Matrix4d rightArmPose = 3;
  bool has_rightarmpose() const;
  private:
  bool _internal_has_rightarmpose() const;
  public:
  void clear_rightarmpose();
  const ::RobotTeleoperate::Matrix4d& rightarmpose() const;
  PROTOBUF_NODISCARD ::RobotTeleoperate::Matrix4d* release_rightarmpose();
  ::RobotTeleoperate::Matrix4d* mutable_rightarmpose();
  void set_allocated_rightarmpose(::RobotTeleoperate::Matrix4d* rightarmpose);
  private:
  const ::RobotTeleoperate::Matrix4d& _internal_rightarmpose() const;
  ::RobotTeleoperate::Matrix4d* _internal_mutable_rightarmpose();
  public:
  void unsafe_arena_set_allocated_rightarmpose(
      ::RobotTeleoperate::Matrix4d* rightarmpose);
  ::RobotTeleoperate::Matrix4d* unsafe_arena_release_rightarmpose();

  // .RobotTeleoperate.HandPositions leftHandPositions = 4;
  bool has_lefthandpositions() const;
  private:
  bool _internal_has_lefthandpositions() const;
  public:
  void clear_lefthandpositions();
  const ::RobotTeleoperate::HandPositions& lefthandpositions() const;
  PROTOBUF_NODISCARD ::RobotTeleoperate::HandPositions* release_lefthandpositions();
  ::RobotTeleoperate::HandPositions* mutable_lefthandpositions();
  void set_allocated_lefthandpositions(::RobotTeleoperate::HandPositions* lefthandpositions);
  private:
  const ::RobotTeleoperate::HandPositions& _internal_lefthandpositions() const;
  ::RobotTeleoperate::HandPositions* _internal_mutable_lefthandpositions();
  public:
  void unsafe_arena_set_allocated_lefthandpositions(
      ::RobotTeleoperate::HandPositions* lefthandpositions);
  ::RobotTeleoperate::HandPositions* unsafe_arena_release_lefthandpositions();

  // .RobotTeleoperate.HandPositions rightHandPositions = 5;
  bool has_righthandpositions() const;
  private:
  bool _internal_has_righthandpositions() const;
  public:
  void clear_righthandpositions();
  const ::RobotTeleoperate::HandPositions& righthandpositions() const;
  PROTOBUF_NODISCARD ::RobotTeleoperate::HandPositions* release_righthandpositions();
  ::RobotTeleoperate::HandPositions* mutable_righthandpositions();
  void set_allocated_righthandpositions(::RobotTeleoperate::HandPositions* righthandpositions);
  private:
  const ::RobotTeleoperate::HandPositions& _internal_righthandpositions() const;
  ::RobotTeleoperate::HandPositions* _internal_mutable_righthandpositions();
  public:
  void unsafe_arena_set_allocated_righthandpositions(
      ::RobotTeleoperate::HandPositions* righthandpositions);
  ::RobotTeleoperate::HandPositions* unsafe_arena_release_righthandpositions();

  // @@protoc_insertion_point(class_scope:RobotTeleoperate.VisionProData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::RobotTeleoperate::Matrix4d* headpzose_;
    ::RobotTeleoperate::Matrix4d* leftarmpose_;
    ::RobotTeleoperate::Matrix4d* rightarmpose_;
    ::RobotTeleoperate::HandPositions* lefthandpositions_;
    ::RobotTeleoperate::HandPositions* righthandpositions_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_VisionProData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Matrix4d

// repeated double data = 1;
inline int Matrix4d::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int Matrix4d::data_size() const {
  return _internal_data_size();
}
inline void Matrix4d::clear_data() {
  _impl_.data_.Clear();
}
inline double Matrix4d::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline double Matrix4d::data(int index) const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.Matrix4d.data)
  return _internal_data(index);
}
inline void Matrix4d::set_data(int index, double value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:RobotTeleoperate.Matrix4d.data)
}
inline void Matrix4d::_internal_add_data(double value) {
  _impl_.data_.Add(value);
}
inline void Matrix4d::add_data(double value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:RobotTeleoperate.Matrix4d.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Matrix4d::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Matrix4d::data() const {
  // @@protoc_insertion_point(field_list:RobotTeleoperate.Matrix4d.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Matrix4d::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Matrix4d::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:RobotTeleoperate.Matrix4d.data)
  return _internal_mutable_data();
}

// -------------------------------------------------------------------

// Point3d

// double x = 1;
inline void Point3d::clear_x() {
  _impl_.x_ = 0;
}
inline double Point3d::_internal_x() const {
  return _impl_.x_;
}
inline double Point3d::x() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.Point3d.x)
  return _internal_x();
}
inline void Point3d::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Point3d::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:RobotTeleoperate.Point3d.x)
}

// double y = 2;
inline void Point3d::clear_y() {
  _impl_.y_ = 0;
}
inline double Point3d::_internal_y() const {
  return _impl_.y_;
}
inline double Point3d::y() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.Point3d.y)
  return _internal_y();
}
inline void Point3d::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Point3d::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:RobotTeleoperate.Point3d.y)
}

// double z = 3;
inline void Point3d::clear_z() {
  _impl_.z_ = 0;
}
inline double Point3d::_internal_z() const {
  return _impl_.z_;
}
inline double Point3d::z() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.Point3d.z)
  return _internal_z();
}
inline void Point3d::_internal_set_z(double value) {
  
  _impl_.z_ = value;
}
inline void Point3d::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:RobotTeleoperate.Point3d.z)
}

// -------------------------------------------------------------------

// HandPositions

// repeated .RobotTeleoperate.Point3d joints = 1;
inline int HandPositions::_internal_joints_size() const {
  return _impl_.joints_.size();
}
inline int HandPositions::joints_size() const {
  return _internal_joints_size();
}
inline void HandPositions::clear_joints() {
  _impl_.joints_.Clear();
}
inline ::RobotTeleoperate::Point3d* HandPositions::mutable_joints(int index) {
  // @@protoc_insertion_point(field_mutable:RobotTeleoperate.HandPositions.joints)
  return _impl_.joints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RobotTeleoperate::Point3d >*
HandPositions::mutable_joints() {
  // @@protoc_insertion_point(field_mutable_list:RobotTeleoperate.HandPositions.joints)
  return &_impl_.joints_;
}
inline const ::RobotTeleoperate::Point3d& HandPositions::_internal_joints(int index) const {
  return _impl_.joints_.Get(index);
}
inline const ::RobotTeleoperate::Point3d& HandPositions::joints(int index) const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.HandPositions.joints)
  return _internal_joints(index);
}
inline ::RobotTeleoperate::Point3d* HandPositions::_internal_add_joints() {
  return _impl_.joints_.Add();
}
inline ::RobotTeleoperate::Point3d* HandPositions::add_joints() {
  ::RobotTeleoperate::Point3d* _add = _internal_add_joints();
  // @@protoc_insertion_point(field_add:RobotTeleoperate.HandPositions.joints)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RobotTeleoperate::Point3d >&
HandPositions::joints() const {
  // @@protoc_insertion_point(field_list:RobotTeleoperate.HandPositions.joints)
  return _impl_.joints_;
}

// -------------------------------------------------------------------

// VisionProData

// .RobotTeleoperate.Matrix4d headPzose = 1;
inline bool VisionProData::_internal_has_headpzose() const {
  return this != internal_default_instance() && _impl_.headpzose_ != nullptr;
}
inline bool VisionProData::has_headpzose() const {
  return _internal_has_headpzose();
}
inline void VisionProData::clear_headpzose() {
  if (GetArenaForAllocation() == nullptr && _impl_.headpzose_ != nullptr) {
    delete _impl_.headpzose_;
  }
  _impl_.headpzose_ = nullptr;
}
inline const ::RobotTeleoperate::Matrix4d& VisionProData::_internal_headpzose() const {
  const ::RobotTeleoperate::Matrix4d* p = _impl_.headpzose_;
  return p != nullptr ? *p : reinterpret_cast<const ::RobotTeleoperate::Matrix4d&>(
      ::RobotTeleoperate::_Matrix4d_default_instance_);
}
inline const ::RobotTeleoperate::Matrix4d& VisionProData::headpzose() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.VisionProData.headPzose)
  return _internal_headpzose();
}
inline void VisionProData::unsafe_arena_set_allocated_headpzose(
    ::RobotTeleoperate::Matrix4d* headpzose) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.headpzose_);
  }
  _impl_.headpzose_ = headpzose;
  if (headpzose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RobotTeleoperate.VisionProData.headPzose)
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::release_headpzose() {
  
  ::RobotTeleoperate::Matrix4d* temp = _impl_.headpzose_;
  _impl_.headpzose_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::unsafe_arena_release_headpzose() {
  // @@protoc_insertion_point(field_release:RobotTeleoperate.VisionProData.headPzose)
  
  ::RobotTeleoperate::Matrix4d* temp = _impl_.headpzose_;
  _impl_.headpzose_ = nullptr;
  return temp;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::_internal_mutable_headpzose() {
  
  if (_impl_.headpzose_ == nullptr) {
    auto* p = CreateMaybeMessage<::RobotTeleoperate::Matrix4d>(GetArenaForAllocation());
    _impl_.headpzose_ = p;
  }
  return _impl_.headpzose_;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::mutable_headpzose() {
  ::RobotTeleoperate::Matrix4d* _msg = _internal_mutable_headpzose();
  // @@protoc_insertion_point(field_mutable:RobotTeleoperate.VisionProData.headPzose)
  return _msg;
}
inline void VisionProData::set_allocated_headpzose(::RobotTeleoperate::Matrix4d* headpzose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.headpzose_;
  }
  if (headpzose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(headpzose);
    if (message_arena != submessage_arena) {
      headpzose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, headpzose, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.headpzose_ = headpzose;
  // @@protoc_insertion_point(field_set_allocated:RobotTeleoperate.VisionProData.headPzose)
}

// .RobotTeleoperate.Matrix4d leftArmPose = 2;
inline bool VisionProData::_internal_has_leftarmpose() const {
  return this != internal_default_instance() && _impl_.leftarmpose_ != nullptr;
}
inline bool VisionProData::has_leftarmpose() const {
  return _internal_has_leftarmpose();
}
inline void VisionProData::clear_leftarmpose() {
  if (GetArenaForAllocation() == nullptr && _impl_.leftarmpose_ != nullptr) {
    delete _impl_.leftarmpose_;
  }
  _impl_.leftarmpose_ = nullptr;
}
inline const ::RobotTeleoperate::Matrix4d& VisionProData::_internal_leftarmpose() const {
  const ::RobotTeleoperate::Matrix4d* p = _impl_.leftarmpose_;
  return p != nullptr ? *p : reinterpret_cast<const ::RobotTeleoperate::Matrix4d&>(
      ::RobotTeleoperate::_Matrix4d_default_instance_);
}
inline const ::RobotTeleoperate::Matrix4d& VisionProData::leftarmpose() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.VisionProData.leftArmPose)
  return _internal_leftarmpose();
}
inline void VisionProData::unsafe_arena_set_allocated_leftarmpose(
    ::RobotTeleoperate::Matrix4d* leftarmpose) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.leftarmpose_);
  }
  _impl_.leftarmpose_ = leftarmpose;
  if (leftarmpose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RobotTeleoperate.VisionProData.leftArmPose)
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::release_leftarmpose() {
  
  ::RobotTeleoperate::Matrix4d* temp = _impl_.leftarmpose_;
  _impl_.leftarmpose_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::unsafe_arena_release_leftarmpose() {
  // @@protoc_insertion_point(field_release:RobotTeleoperate.VisionProData.leftArmPose)
  
  ::RobotTeleoperate::Matrix4d* temp = _impl_.leftarmpose_;
  _impl_.leftarmpose_ = nullptr;
  return temp;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::_internal_mutable_leftarmpose() {
  
  if (_impl_.leftarmpose_ == nullptr) {
    auto* p = CreateMaybeMessage<::RobotTeleoperate::Matrix4d>(GetArenaForAllocation());
    _impl_.leftarmpose_ = p;
  }
  return _impl_.leftarmpose_;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::mutable_leftarmpose() {
  ::RobotTeleoperate::Matrix4d* _msg = _internal_mutable_leftarmpose();
  // @@protoc_insertion_point(field_mutable:RobotTeleoperate.VisionProData.leftArmPose)
  return _msg;
}
inline void VisionProData::set_allocated_leftarmpose(::RobotTeleoperate::Matrix4d* leftarmpose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.leftarmpose_;
  }
  if (leftarmpose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(leftarmpose);
    if (message_arena != submessage_arena) {
      leftarmpose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, leftarmpose, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.leftarmpose_ = leftarmpose;
  // @@protoc_insertion_point(field_set_allocated:RobotTeleoperate.VisionProData.leftArmPose)
}

// .RobotTeleoperate.Matrix4d rightArmPose = 3;
inline bool VisionProData::_internal_has_rightarmpose() const {
  return this != internal_default_instance() && _impl_.rightarmpose_ != nullptr;
}
inline bool VisionProData::has_rightarmpose() const {
  return _internal_has_rightarmpose();
}
inline void VisionProData::clear_rightarmpose() {
  if (GetArenaForAllocation() == nullptr && _impl_.rightarmpose_ != nullptr) {
    delete _impl_.rightarmpose_;
  }
  _impl_.rightarmpose_ = nullptr;
}
inline const ::RobotTeleoperate::Matrix4d& VisionProData::_internal_rightarmpose() const {
  const ::RobotTeleoperate::Matrix4d* p = _impl_.rightarmpose_;
  return p != nullptr ? *p : reinterpret_cast<const ::RobotTeleoperate::Matrix4d&>(
      ::RobotTeleoperate::_Matrix4d_default_instance_);
}
inline const ::RobotTeleoperate::Matrix4d& VisionProData::rightarmpose() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.VisionProData.rightArmPose)
  return _internal_rightarmpose();
}
inline void VisionProData::unsafe_arena_set_allocated_rightarmpose(
    ::RobotTeleoperate::Matrix4d* rightarmpose) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rightarmpose_);
  }
  _impl_.rightarmpose_ = rightarmpose;
  if (rightarmpose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RobotTeleoperate.VisionProData.rightArmPose)
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::release_rightarmpose() {
  
  ::RobotTeleoperate::Matrix4d* temp = _impl_.rightarmpose_;
  _impl_.rightarmpose_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::unsafe_arena_release_rightarmpose() {
  // @@protoc_insertion_point(field_release:RobotTeleoperate.VisionProData.rightArmPose)
  
  ::RobotTeleoperate::Matrix4d* temp = _impl_.rightarmpose_;
  _impl_.rightarmpose_ = nullptr;
  return temp;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::_internal_mutable_rightarmpose() {
  
  if (_impl_.rightarmpose_ == nullptr) {
    auto* p = CreateMaybeMessage<::RobotTeleoperate::Matrix4d>(GetArenaForAllocation());
    _impl_.rightarmpose_ = p;
  }
  return _impl_.rightarmpose_;
}
inline ::RobotTeleoperate::Matrix4d* VisionProData::mutable_rightarmpose() {
  ::RobotTeleoperate::Matrix4d* _msg = _internal_mutable_rightarmpose();
  // @@protoc_insertion_point(field_mutable:RobotTeleoperate.VisionProData.rightArmPose)
  return _msg;
}
inline void VisionProData::set_allocated_rightarmpose(::RobotTeleoperate::Matrix4d* rightarmpose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rightarmpose_;
  }
  if (rightarmpose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rightarmpose);
    if (message_arena != submessage_arena) {
      rightarmpose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rightarmpose, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.rightarmpose_ = rightarmpose;
  // @@protoc_insertion_point(field_set_allocated:RobotTeleoperate.VisionProData.rightArmPose)
}

// .RobotTeleoperate.HandPositions leftHandPositions = 4;
inline bool VisionProData::_internal_has_lefthandpositions() const {
  return this != internal_default_instance() && _impl_.lefthandpositions_ != nullptr;
}
inline bool VisionProData::has_lefthandpositions() const {
  return _internal_has_lefthandpositions();
}
inline void VisionProData::clear_lefthandpositions() {
  if (GetArenaForAllocation() == nullptr && _impl_.lefthandpositions_ != nullptr) {
    delete _impl_.lefthandpositions_;
  }
  _impl_.lefthandpositions_ = nullptr;
}
inline const ::RobotTeleoperate::HandPositions& VisionProData::_internal_lefthandpositions() const {
  const ::RobotTeleoperate::HandPositions* p = _impl_.lefthandpositions_;
  return p != nullptr ? *p : reinterpret_cast<const ::RobotTeleoperate::HandPositions&>(
      ::RobotTeleoperate::_HandPositions_default_instance_);
}
inline const ::RobotTeleoperate::HandPositions& VisionProData::lefthandpositions() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.VisionProData.leftHandPositions)
  return _internal_lefthandpositions();
}
inline void VisionProData::unsafe_arena_set_allocated_lefthandpositions(
    ::RobotTeleoperate::HandPositions* lefthandpositions) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.lefthandpositions_);
  }
  _impl_.lefthandpositions_ = lefthandpositions;
  if (lefthandpositions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RobotTeleoperate.VisionProData.leftHandPositions)
}
inline ::RobotTeleoperate::HandPositions* VisionProData::release_lefthandpositions() {
  
  ::RobotTeleoperate::HandPositions* temp = _impl_.lefthandpositions_;
  _impl_.lefthandpositions_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::RobotTeleoperate::HandPositions* VisionProData::unsafe_arena_release_lefthandpositions() {
  // @@protoc_insertion_point(field_release:RobotTeleoperate.VisionProData.leftHandPositions)
  
  ::RobotTeleoperate::HandPositions* temp = _impl_.lefthandpositions_;
  _impl_.lefthandpositions_ = nullptr;
  return temp;
}
inline ::RobotTeleoperate::HandPositions* VisionProData::_internal_mutable_lefthandpositions() {
  
  if (_impl_.lefthandpositions_ == nullptr) {
    auto* p = CreateMaybeMessage<::RobotTeleoperate::HandPositions>(GetArenaForAllocation());
    _impl_.lefthandpositions_ = p;
  }
  return _impl_.lefthandpositions_;
}
inline ::RobotTeleoperate::HandPositions* VisionProData::mutable_lefthandpositions() {
  ::RobotTeleoperate::HandPositions* _msg = _internal_mutable_lefthandpositions();
  // @@protoc_insertion_point(field_mutable:RobotTeleoperate.VisionProData.leftHandPositions)
  return _msg;
}
inline void VisionProData::set_allocated_lefthandpositions(::RobotTeleoperate::HandPositions* lefthandpositions) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.lefthandpositions_;
  }
  if (lefthandpositions) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(lefthandpositions);
    if (message_arena != submessage_arena) {
      lefthandpositions = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, lefthandpositions, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.lefthandpositions_ = lefthandpositions;
  // @@protoc_insertion_point(field_set_allocated:RobotTeleoperate.VisionProData.leftHandPositions)
}

// .RobotTeleoperate.HandPositions rightHandPositions = 5;
inline bool VisionProData::_internal_has_righthandpositions() const {
  return this != internal_default_instance() && _impl_.righthandpositions_ != nullptr;
}
inline bool VisionProData::has_righthandpositions() const {
  return _internal_has_righthandpositions();
}
inline void VisionProData::clear_righthandpositions() {
  if (GetArenaForAllocation() == nullptr && _impl_.righthandpositions_ != nullptr) {
    delete _impl_.righthandpositions_;
  }
  _impl_.righthandpositions_ = nullptr;
}
inline const ::RobotTeleoperate::HandPositions& VisionProData::_internal_righthandpositions() const {
  const ::RobotTeleoperate::HandPositions* p = _impl_.righthandpositions_;
  return p != nullptr ? *p : reinterpret_cast<const ::RobotTeleoperate::HandPositions&>(
      ::RobotTeleoperate::_HandPositions_default_instance_);
}
inline const ::RobotTeleoperate::HandPositions& VisionProData::righthandpositions() const {
  // @@protoc_insertion_point(field_get:RobotTeleoperate.VisionProData.rightHandPositions)
  return _internal_righthandpositions();
}
inline void VisionProData::unsafe_arena_set_allocated_righthandpositions(
    ::RobotTeleoperate::HandPositions* righthandpositions) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.righthandpositions_);
  }
  _impl_.righthandpositions_ = righthandpositions;
  if (righthandpositions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:RobotTeleoperate.VisionProData.rightHandPositions)
}
inline ::RobotTeleoperate::HandPositions* VisionProData::release_righthandpositions() {
  
  ::RobotTeleoperate::HandPositions* temp = _impl_.righthandpositions_;
  _impl_.righthandpositions_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::RobotTeleoperate::HandPositions* VisionProData::unsafe_arena_release_righthandpositions() {
  // @@protoc_insertion_point(field_release:RobotTeleoperate.VisionProData.rightHandPositions)
  
  ::RobotTeleoperate::HandPositions* temp = _impl_.righthandpositions_;
  _impl_.righthandpositions_ = nullptr;
  return temp;
}
inline ::RobotTeleoperate::HandPositions* VisionProData::_internal_mutable_righthandpositions() {
  
  if (_impl_.righthandpositions_ == nullptr) {
    auto* p = CreateMaybeMessage<::RobotTeleoperate::HandPositions>(GetArenaForAllocation());
    _impl_.righthandpositions_ = p;
  }
  return _impl_.righthandpositions_;
}
inline ::RobotTeleoperate::HandPositions* VisionProData::mutable_righthandpositions() {
  ::RobotTeleoperate::HandPositions* _msg = _internal_mutable_righthandpositions();
  // @@protoc_insertion_point(field_mutable:RobotTeleoperate.VisionProData.rightHandPositions)
  return _msg;
}
inline void VisionProData::set_allocated_righthandpositions(::RobotTeleoperate::HandPositions* righthandpositions) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.righthandpositions_;
  }
  if (righthandpositions) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(righthandpositions);
    if (message_arena != submessage_arena) {
      righthandpositions = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, righthandpositions, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.righthandpositions_ = righthandpositions;
  // @@protoc_insertion_point(field_set_allocated:RobotTeleoperate.VisionProData.rightHandPositions)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace RobotTeleoperate

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_VisionProData_2eproto
