# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VisionProData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13VisionProData.proto\x12\x10RobotTeleoperate\"\x18\n\x08Matrix4d\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"*\n\x07Point3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\":\n\rHandPositions\x12)\n\x06joints\x18\x01 \x03(\x0b\x32\x19.RobotTeleoperate.Point3d\"\x9a\x02\n\rVisionProData\x12-\n\theadPzose\x18\x01 \x01(\x0b\x32\x1a.RobotTeleoperate.Matrix4d\x12/\n\x0bleftArmPose\x18\x02 \x01(\x0b\x32\x1a.RobotTeleoperate.Matrix4d\x12\x30\n\x0crightArmPose\x18\x03 \x01(\x0b\x32\x1a.RobotTeleoperate.Matrix4d\x12:\n\x11leftHandPositions\x18\x04 \x01(\x0b\x32\x1f.RobotTeleoperate.HandPositions\x12;\n\x12rightHandPositions\x18\x05 \x01(\x0b\x32\x1f.RobotTeleoperate.HandPositionsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VisionProData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATRIX4D._serialized_start=41
  _MATRIX4D._serialized_end=65
  _POINT3D._serialized_start=67
  _POINT3D._serialized_end=109
  _HANDPOSITIONS._serialized_start=111
  _HANDPOSITIONS._serialized_end=169
  _VISIONPRODATA._serialized_start=172
  _VISIONPRODATA._serialized_end=454
# @@protoc_insertion_point(module_scope)
